### PR TITLE
delete items during invoice deletion and refactor 3

### LINKED ISSUE #39: Refactor3
- Review relationship between Item and Invoice
- Delete item when deleting the invoices

### PR DESCRIPTION
**Pull request by sebinfrancis**
#39

### CODE REVIEW

**Review by j-tanz — DISMISSED** [review]

**Review by selvasabapathy — APPROVED** [review]
LGTM

**Review by selvasabapathy — CHANGES_REQUESTED** [review]
Merge company

**Review by selvasabapathy — APPROVED** [review]
LGTM

**Review by j-tanz — APPROVED** [review]
LGTM

**Pull request merged**
